version: '3'
services:
#      db:
#        image: "postgres"
#        environment:
#          - POSTGRES_USER=username
#          - POSTGRES_PASSWORD=password
#        volumes:
#          - /opt/data/post/:/var/lib/postgresql/data/
#        ports:
#          - '5432:5432'
      db:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_DATABASE: 'db'
          MYSQL_USER: 'user'
          MYSQL_PASSWORD: 'password'
          MYSQL_ROOT_PASSWORD: 'password'
          MYSQL_TCP_PORT: 5555
        ports:
          - '5555:5555'
        expose:
          - '5555'
        volumes:
          - /opt/data/mysql/:/var/lib/mysql

